meta:
  created: "2026-02-09T17:23:53Z"
patterns:
  - should_i: \"Should I {{ACTION}}?\"
  - do_i_need: \"Do I need {{THING}}?\"
  - is_it_worth_it: \"Is {{THING}} worth it?\"
rules:
  - pre-extraction
  - uncertainty exists
  - restraint allowed
